### ISSUE TITLE
WebView didn't load PayPal credit cart payment form

### ISSUE THREAD

**Issue by carlotnx** [tidev/titanium_mobile#11442]
**Describe the bug**
WebView isn't loading PayPal credit cart payment form

**To Reproduce**
1. Reach a PayPal credi cart payment form through WebView ([directly](https://www.pizzartfano.com/Pagamento/metodo:paypal_cc/id:59238/mobile:1/) or with "pay with debit or credit cart" button)

**Expected behavior**
See the form fields (name, lastname, card no, ecc...)

**Environment**
Titanium SDK version: 8 to 8.3.0
CLI version: 7.1.2

**Logs**:
attached here with screenshots and test link / app:
https://jira.appcelerator.org/browse/AC-6467

**Comment by m1ga** [comment]
```
Refused to execute inline event handler because it violates the following Content Security Policy directive: 
"script-src 'nonce-1DLuTAqRoIviJcFw20YJSHgrT4L7wWE7qFyZiyV4jRmEmTk0'
 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline' 'unsafe-eval'". 
Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```
e.g. https://github.com/paypal/paypal-checkout-components/issues/447 
there are multiple errors with paypal + chrome + CSP:
https://www.google.com/search?client=firefox-b-d&q=paypal+Content+Security+Policy
not sure if that is a Ti error

**Comment by carlotnx** [comment]
Those errors are in chrome (and all other browser) too, but didn't breaks the page, neither in native WebView

**Comment by m1ga** [comment]
I see. I've tried it with SDK 9 and tried a `PermissionRequest` patch on the WebView but it isn't working either

**Comment by carlotnx** [comment]
I can add more details: the problem is related to css vh propriety.
In Titanium's WebView implementation isn't work properly and any related size results in 0 pixel.
I've added a test page to the test app and screenshot.

Meanwhile I had to implement PayPal buttons, that use the same page in a fixed height iframe and works in Titanium WebView.

**Comment by antonioduran** [comment]
Hello @carlotnx . Good afternoon / evening.

I have implemented paypal in these days using a local html, and everything is working good.

Suggestion: Please try to add this property to your webview:

```
"#mWebView" : {
	borderRadius : 1
}
```
,and try again.

Please let me know how it goes, and whether you have any doubt or question.

Thanks, and best,
Antonio Duran.

**Comment by carlotnx** [comment]
thank you for the workaround
borderRadius makes css vh propery work correctly and I can browse PayPal credit card page correctly

...but why???
vh propery is widely used in the web and nobody found this problem?

**Comment by hansemannn** [comment]
Until a more extensive fix is available, I hope that the `borderRadius` workaround is feasible here. Thanks everyone!
