### ISSUE TITLE
Android: "unregisterNetworkCallback" not working correctly

### ISSUE THREAD

**Issue by VenkateshBhagat** [tidev/titanium_mobile#11491]
Currently i am working on android 10 wifi connectivity manager, as of now i am binding process to particular network and calling unregisternetworkcallback() in onlost() callback to relase that network in order to bind another network which is having same ssid and password, i am failed to do so. I am using network speifier to select the network to be connected, but since it was binded with precious n/w its unable to release that n/w. But when i reboot the phone or reinstall the app it works with another network

**Comment by m1ga** [comment]
I think that this is not related to the SDK itself. `onlost` or `unregisternetworkcallback` are not part the SDK. So I'll close this. Feel free to create a new issue if you stiil have this issue but please add more information.
