### ISSUE TITLE
Android Webview android:targetSdkVersion=30+ access local files default changed

### ISSUE THREAD

**Issue by markive** [tidev/titanium_mobile#13188]
With Android SDK Version 30+ by default a webview will not have access to local assets like images accessed through file://.

This is therefore a breaking change since previously the default was for this setting to be true.

Android documentation of the change: https://developer.android.com/reference/android/webkit/WebSettings#setAllowFileAccess(boolean)

Stackoverflow dealing with the problem natively: https://stackoverflow.com/a/63846853/181197

I will submit a PR so that this becomes a property.

**Comment by markive** [comment]
Please see new PR where I have implemented setAllowFileAccess / getAllowFileAccess as a full Android property. Thanks!

**Comment by Xlinx64** [comment]
Is there any progress here?

**Comment by Xlinx64** [comment]
Hyperloop doesn’t work in my app so I had to build a custom sdk. That is not optimal for production. But I had no other choice.

**Comment by akinsoftyazilim42** [comment]
> Hyperloop doesn’t work in my app so I had to build a custom sdk. That is not optimal for production. But I had no other choice.

How were you to build a custom sdk. I don't know this. are There help videos or documents?

**Comment by Xlinx64** [comment]
@m1ga I used hyperloop for some time but after the update to titanium 10 the webview didnt load anymore. I couldnt really figure out why the hyperloop broke it.

**Comment by m1ga** [comment]
A last question: You've added `setAllowFileAccess` to the SDK, right? One concern in the PR was that Google will eventually flag the app as insecure. Do you have your app in store and did Google complain about it?

**Comment by Xlinx64** [comment]
I didnt have a problem with this. I already updated the app 2 times in the playstore and there where no complaints from google.
