### ISSUE TITLE
Android: Random crash with map view in Ti.UI.ListSection footer

### ISSUE THREAD

**Issue by drauggres** [tidev/titanium_mobile#13243]
https://jira.appcelerator.org/browse/TIMOB-28583

<details><summary>Exception</summary>

   ```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: ti.map.test, PID: 29094
E AndroidRuntime: java.lang.IllegalArgumentException: No view found for id 0x2 (unknown) for fragment SupportMapFragment{ab59c34} (12aebe3e-06b7-46e3-b9ca-2d53d2ec238d id=0x2)
E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
E AndroidRuntime:        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
   ```
</details>

<details><summary>App sample</summary>

```javascript
const mapView = Ti.UI.createView({
  height: 200
});
mapView.add(require('ti.map').createView());

const win = Ti.UI.createWindow({
  title: 'test',
  backgroundColor: 'gray'
});

function addListView() {
  var listView = Ti.UI.createListView({
    footerView: mapView,
    templates: {
      test: {
        childTemplates: [{
          type: 'Ti.UI.View',
          childTemplates: [{
            type: 'Ti.UI.Label',
            bindId: 'label',
            properties: {
              color: 'black',
              bindId: 'label'
            }
          }],
          properties: {
            width: Ti.UI.FILL,
            height: 200,
            cardUseCompatPadding: true,
            backgroundColor: 'white'
          }
        }]
      }
    },
    defaultItemTemplate: 'test'
  });
  var section = Ti.UI.createListSection();
  var items = [];

  for (let i = 0; i < 20; i++) {
    items.push({
      label: {
        text: 'item ' + i
      },
      template: 'test'
    })
  }

  section.setItems(items);
  listView.sections = [section];
  win.add(listView);
}

win.addEventListener('open', function() {
  addListView();
})
win.open();

```
</details>

[Original discussion](https://github.com/appcelerator/titanium_mobile/pull/12524#pullrequestreview-851812253)

I think the reason is a race condition between [FragmentTransaction](https://github.com/appcelerator/titanium_mobile/blob/2dad43e47e6db455ce6d9f852082ab766bfd81d8/android/titanium/src/java/org/appcelerator/titanium/view/TiUIFragment.java#L50-L55) and [attaching view to a window](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter#onViewAttachedToWindow(VH)), i.e. app will crash when the transaction is executed before the view has been attached.

P.S. somehow connecting to the app with debugger make it harder to reproduce the problem.

**Comment by m1ga** [comment]
maybe this can help to debug a bit more: https://stackoverflow.com/questions/42205827/add-fragment-in-recyclerview-viewholder

**Comment by hansemannn** [comment]
I hereby offer a bounty for fixing this issue in the SDK and/or ti.map. Is there anyone able to hack on this?

**Comment by drauggres** [comment]
Doesn't the trick with `postlayout` work?

**Comment by hansemannn** [comment]
It does work so far, but the rendering is (visibly) delayed and iOS lags as well, causing a platform-specific implementation of the map. A fixed Android version would eliminate those issues.

**Comment by hansemannn** [comment]
Actually, it still rarely crashes with the same error ` E/com.appc.test Invalid ID 0x00000005.`

**Comment by m1ga** [comment]
@hansemannn  can you please try this one: 
[ti.map-android-5.3.5.zip](https://github.com/appcelerator/titanium_mobile/files/7972957/ti.map-android-5.3.5.zip)
I moved the TiUIMapView to `extends TiUIView`. My test app with a footerView works fine.

**Comment by hansemannn** [comment]
Thanks Michael! Is there a commit I could  cherry pick? We use a highly adjusted version of ti.map 😗

**Comment by m1ga** [comment]
Sure: https://github.com/m1ga/ti.map/tree/testing
I didn't do any tests besides opening the app. Had to remove the override at `interceptTouchEvent`

**Comment by hansemannn** [comment]
Will test asap already! Note for later cleanup: Rename layout_lottie with layout_map 😇

**Comment by m1ga** [comment]
yes :smile: At the moment I'm even not sure if the XML is needed at all. Was testing multiple stuff at once :rofl:

**Comment by hansemannn** [comment]
Unfortunately I cannot test it, yet, because it collides with ti.animation:
```
[ERROR] TiExceptionHandler: Error: Attempt to invoke virtual method 'void com.airbnb.lottie.LottieAnimationView.setScaleType(android.widget.ImageView$ScaleType)' on a null object reference
```
Likely because of the same XML file? Will test later then!

**Comment by m1ga** [comment]
oh interesting. I've updated the name

**Comment by hansemannn** [comment]
Interesting, thank you! Now it renders, but none of the properties are applied anymore (like annotations, mapStyle, padding etc.)

**Comment by m1ga** [comment]
ok, but it looks like we can change ti.map instead of stuff in the SDK :+1: Makes it a bit quicker to debug.

**Comment by drauggres** [comment]
> ok, but it looks like we can change ti.map instead of stuff in the SDK Makes it a bit quicker to debug.

I don't think so. Internally, you still use a `Fragment`, meaning that the problem (adding two views asynchronously) still there. (I could be wrong. I never really worked with `Fragment`s)

A possible solution would be:
- addind new "view-attached-to-window"-event
- passing it through all child-views when a view is attached (to a window directly or to another view that has already been attached)
- listening for this event in TiUIFragment and executing the [transaction](https://github.com/appcelerator/titanium_mobile/blob/2dad43e47e6db455ce6d9f852082ab766bfd81d8/android/titanium/src/java/org/appcelerator/titanium/view/TiUIFragment.java#L50-L55) when the event is received.

But I'm not sure how it will affect regular views (performance-wise).

**Comment by hansemannn** [comment]
@drauggres Very interested in that approach! Another one could be https://developers.google.com/maps/documentation/android-sdk/lite which may be enough because the map does not have any interaction required

**Comment by m1ga** [comment]
@hansemannn `liteMode` is already supported (2 years :wink: ) but it didn't change anything.

**Comment by hansemannn** [comment]
Then it has to be the recyclerview itself. Worst case, it would need a static generated image..This now really shows the Titanium limits.

**Comment by drauggres** [comment]
@hansemannn please try this patch:
https://github.com/drauggres/titanium_mobile/commit/14859b84cd767a97297e6a207f80debf6d24382a

Though it does not crash, I'm not sure about memory leaks.
Probably we should also override `onDetachedFromWindow` and do something, idk.

**Comment by m1ga** [comment]
:rofl: just doing some tests here too:
![Screenshot_20220203_130355](https://user-images.githubusercontent.com/4334997/152339449-8ce9eb41-4a29-4ccc-b93a-2879a434d012.png)

I'll test it right away, too!

**Comment by m1ga** [comment]
Looking very good :+1: My test app doesn't crash!

**Comment by hansemannn** [comment]
Whaaat? Super excited here!

**Comment by hansemannn** [comment]
@drauggres Unfortunately still crashing sporadically :(

**Comment by m1ga** [comment]
with the same ` No view found for id 0x2 (unknown)` error?

**Comment by hansemannn** [comment]
It's always `E/com.appc.app Invalid ID 0x0000000a.` for us

**Comment by m1ga** [comment]
ah ok, the "no view" part is the next line.
```
E/com.miga.rando: Invalid ID 0x00000002.
TiExceptionHandler: (main) [2590,2701] No view found for id 0x2 (unknown) for fragment SupportMapFragment{59a6fe9} (043b23b5-a8ef-435e-8bd6-0af1a9922127 id=0x2)
TiExceptionHandler:
TiExceptionHandler:     androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
TiExceptionHandler:     androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
TiExceptionHandler:     androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
TiExceptionHandler:     androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
TiExceptionHandler:     androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
TiExceptionHandler:     androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
TiExceptionHandler:     android.os.Handler.handleCallback(Handler.java:938)
TiExceptionHandler:     android.os.Handler.dispatchMessage(Handler.java:99)
TiExceptionHandler:     android.os.Looper.loopOnce(Looper.java:201)
TiExceptionHandler:     android.os.Looper.loop(Looper.java:288)
TiExceptionHandler:     android.app.ActivityThread.main(ActivityThread.java:7839)
TiExceptionHandler:     java.lang.reflect.Method.invoke(Native Method)
TiExceptionHandler:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
TiExceptionHandler:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by hansemannn** [comment]
Checking! Never saw the above trace actually. But maybe crashlytics grabs it away, which I can't think of. Will check with adb logcat.

**Comment by hansemannn** [comment]
When I remove the `postlayout` hack, it currently seems to work..No annoations are rendered, but that may be something else. Still on it using the patch from @drauggres

**Comment by m1ga** [comment]
don't use my patched ti.map version! With the normal ti.map I had annoations and click working

**Comment by hansemannn** [comment]
I don't. Having no changes on ti.map right now, but it could be a migration issue from moving back to the non-postlayout config.

**Comment by hansemannn** [comment]
Okay, so the crashes are now gone completely. What we do notice is that when opening the map view in non-listviews (e.g. own window), the map is always stuck at the equator line, which works 1:1 when changing the SDK version back. It may be fixable by timeout, because we currently use timeouts as well which may need to wait a bit longer now.

**Comment by drauggres** [comment]
My guest is that you set location and do other api calls before map is actually created.

For example:
https://github.com/appcelerator-modules/ti.map/blob/a12d8d34d3a7c7cd672d9142775a304279de0a88/android/src/ti/map/ViewProxy.java#L1329-L1337

**Comment by m1ga** [comment]
liteMode has other issues with the patch. But I can confirm that the polyline is gone and there is a refresh. But my `region` (set at creation) stays

**Comment by drauggres** [comment]
https://github.com/drauggres/ti.map.tests

This app based on code from `android/example` folder from `ti.map` module.
I added case with ListView to "Drawing" tests.
Don't see any problems in either original or modified test with patched SDK.

**Comment by m1ga** [comment]
Nice test app.
If you scroll up again and then down it will refresh the map and the polygons are cone.

Multimap crashed for me the first time:
```
[ERROR] TiExceptionHandler: (main) [2985,3631] com.google.maps.api.android.lib6.impl.ar cannot be cast to android.view.ViewGroup
[ERROR] TiExceptionHandler:
[ERROR] TiExceptionHandler:     androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:504)
[ERROR] TiExceptionHandler:     androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
[ERROR] TiExceptionHandler:     androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
[ERROR] TiExceptionHandler:     androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
[ERROR] TiExceptionHandler:     androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
[ERROR] TiExceptionHandler:     androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
[ERROR] TiExceptionHandler:     android.os.Handler.handleCallback(Handler.java:938)
[ERROR] TiExceptionHandler:     android.os.Handler.dispatchMessage(Handler.java:99)
[ERROR] TiExceptionHandler:     android.os.Looper.loopOnce(Looper.java:201)
[ERROR] TiExceptionHandler:     android.os.Looper.loop(Looper.java:288)
[ERROR] TiExceptionHandler:     android.app.ActivityThread.main(ActivityThread.java:7839)
[ERROR] TiExceptionHandler:     java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiExceptionHandler:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[ERROR] TiExceptionHandler:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
2nd time I could open it (I opened other items before).

**Comment by drauggres** [comment]
> Multimap crashed for me the first time:

Yes, it also crashing in 10.1.1.GA.

**Comment by m1ga** [comment]
ah, wait. That issue is here: https://github.com/appcelerator-modules/ti.map/issues/480 with a "fix" inside.

**Comment by drauggres** [comment]
> If you scroll up again and then down it will refresh the map and the polygons are cone.

On the bright side, now it works more correctly: it frees resources. lol

**Comment by drauggres** [comment]
https://github.com/appcelerator/titanium_mobile/compare/master...drauggres:bug/map_in_listview

**Comment by hansemannn** [comment]
Quick update here: I thought we fixed it already by removing some duplicate re-rendering, but it sometimes happens again now. I will test your PR in more detail now! :)

**Comment by hansemannn** [comment]
I have to reopen this one :( We still get some crashes:
```
java.lang.IllegalArgumentException: 
  at androidx.fragment.app.FragmentStateManager.createView (FragmentStateManager.java:513)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:282)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:2189)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:2100)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:2002)
  at androidx.fragment.app.FragmentManager$5.run (FragmentManager.java:524)
  at android.os.Handler.handleCallback (Handler.java:808)
  at android.os.Handler.dispatchMessage (Handler.java:101)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7529)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:245)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:921)
  ```
  
  A similar crash was reported for RN as well: https://github.com/software-mansion/react-native-screens/issues/463 and it seems like it could be something related to the "FragmentTransaction" class and how it is reused (which would make sense in a ListView context). Happy to sponsor any work on this fix again!
