### ISSUE TITLE
Add autoSize to label

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium_mobile#13244]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Adds a property `autoSize` to Ti.UI.Label. This makes the text fill out the label width/height automatically:
![ezgif-2-2a79fa0f8f](https://user-images.githubusercontent.com/4334997/149623405-647cc8fb-65cf-4511-a3e7-30ba5de63578.gif)
It won't change the fontSize and will restore the old value when you deactivate it. Similar to the `minimumFontSize` but you don't need to define a max/min value. 

### Solution

adding a property `autoSize`

### Platforms

Android

Looking for a parity ticket :)

**Comment by mbender74** [comment]
https://github.com/mbender74/ti.labelextension-ios/tree/master/ios/Classes

**Comment by mbender74** [comment]
I did a module that solve this on iOS
https://github.com/mbender74/ti.labelextension-ios
