### ISSUE TITLE
Android: Anti-aliasing when setting View borderRadius

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium_mobile#13282]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

When setting a borderRadius on a View or Button with a backgroundColor I have some dimmed corners. Looks like there is an anti-aliasing issue. 

There is a "hack" in the code:

https://github.com/appcelerator/titanium_mobile/blob/fe3deddcea07ecb3555673cf2dba8d676fd79611/android/titanium/src/java/org/appcelerator/titanium/view/TiBorderWrapperView.java#L106-L110

https://github.com/appcelerator/titanium_mobile/blob/fe3deddcea07ecb3555673cf2dba8d676fd79611/android/titanium/src/java/org/appcelerator/titanium/view/TiBorderWrapperView.java#L112-L114

but when I remove it it looks better (left side):

![Screenshot_1645895949](https://user-images.githubusercontent.com/4334997/155852967-a4520b17-1953-4f09-a07a-9f38ecbb35f9.png)

Not sure if it has some side-effects yet but it is something we need to look for!

### Expected Behavior

Smooth corners, no dark colors

### Actual behavior

Dark corner pixels

### Reproducible sample

```xml
<Button title="connect"/>
```

```
"Button" : {
  borderRadius: 10,
  backgroundColor: "#399",
  height: 40
}
```

### Steps to reproduce

create a button with the code above

### Platform

Android

### SDK version you are using

10.1.1.GA

**Comment by hansemannn** [comment]
For buttons, the new material button styles are also fine. But bad for cross platform

**Comment by m1ga** [comment]
Just compiled my app with the patch. Only saw two places where there was a difference - but it's better with the patch:
![Screenshot_20220226-191117](https://user-images.githubusercontent.com/4334997/155854557-82ad2f5a-2205-456c-a522-a8b1c70be61d.png)
(top: patched version, bottom: 10.1.1.GA)

**Comment by joecorriere** [comment]
The "patched" version does look much better. Where is the "patch" from? The JIRA ticket seems to have a closed PR.

**Comment by hansemannn** [comment]
@joecorriere It's the changes in [BorderWrapperView.java](https://github.com/appcelerator/titanium_mobile/blob/fe3deddcea07ecb3555673cf2dba8d676fd79611/android/titanium/src/java/org/appcelerator/titanium/view/TiBorderWrapperView.java#L106-L110) and https://github.com/appcelerator/titanium_mobile/blob/fe3deddcea07ecb3555673cf2dba8d676fd79611/android/titanium/src/java/org/appcelerator/titanium/view/TiBorderWrapperView.java#L112-L114

**Comment by m1ga** [comment]
@joecorriere I'll do a PR later so you can get the SDK from the artifact and test it yourself. Might add minLevel check around it if it is useful for older Android SDKs

**Comment by hansemannn** [comment]
The ticket mentioned Android 4.2.2, so it'be interesting to know if it was still an issue with Android 6/7/x (to add the guard based on where it was fixed)

**Comment by m1ga** [comment]
In my tests this issue was only with Android12+
https://github.com/appcelerator/titanium_mobile/pull/13283

**Comment by m1ga** [comment]
As the description in the original ticket says: 
> While the PR does not fully fix the issue for all use cases, the problem is mitigated.
![Screenshot_1645963078](https://user-images.githubusercontent.com/4334997/155882497-13371196-18d9-4698-9c24-229265f2840e.png)

the is (and was) still a small white border (e.g. in the right view) but it is not really visible on your device. So at some point we might need to make a proper fix for that. But Android 12+ has a dark corner that is very visible and the PR above removes that. Tested it with 12 and 13
