### ISSUE TITLE
CLI: Speed up SDK builds

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium_mobile#13285]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

When building the SDK I've saw that it is using the highests compression level. 
https://github.com/appcelerator/titanium_mobile/blob/fe3deddcea07ecb3555673cf2dba8d676fd79611/build/lib/packager.js#L34

### Solution

I've did some tests with `-1` and `-0`:

```
cleanbuild

-9: 2m32,798s    97,2 MiB (101.939.062)
-1: 2m11,754s   104,3 MiB (109.412.245)
-0: 1m27,539s   229,7 MiB (240.816.659)

-----

without clean

-9: 1m12,909s
-1: 0m55,673s
-0: 0m33,258s

-----

without install

-9: 0m43,754s
-1: 0m34,358s
-0: 0m27,016s 
```

`-0` has the biggers file (229MB) but it builds 1min faster than the current `-9` (97MB). But for a local build I would be fine with the bigger ZIP file.

So perhaps a `--fastCompile` parameter would be nice to set the compression method to `-0`. 
Even for the build server a `-1` with 104MB and 20sec faster would be great.

### Platforms

CLI

**Comment by cb1kenobi** [comment]
While build times for production builds are not an issue, I certainly can appreciate a faster SDK build for development.

What we used to do is only build a specific platform instead of the whole SDK as well as skip the .zip file generation/extraction and simply copy the files into the `~/Library/Application Support/Titanium/mobilesdk/osx/<sdk>/`.

One thing we could do is introduce a new `--fast` (or something) flag that sets the compression level to `-0`.

**Comment by m1ga** [comment]
Thought about skipping the ZIP too. Have to check that. But I think the `-0` might be easier to implement than the ZIP skip and copy part. And the 30sec for a local build (without clean) is very good already.

Oh, I only build the Linux part :wink:

**Comment by ewanharris** [comment]
Does the [--symlink](https://github.com/appcelerator/titanium_mobile/blob/79a94f746b4971af4b10416761b779c8a431ed04/build/scons-cleanbuild.js#L11) flag on the `cleanbuild` command combined with [--skip-zip](https://github.com/appcelerator/titanium_mobile/blob/79a94f746b4971af4b10416761b779c8a431ed04/build/scons-cleanbuild.js#L13) produce a noticeable difference?

**Comment by m1ga** [comment]
I'll close this one. Did some more tests and added the parameter...but at the end I've found out that I was not passing `--skip-zip` to the correct script :facepalm:  

I've added two shortcuts for local `--skip-zip` builds in https://github.com/tidev/titanium_mobile/pull/13391
