### ISSUE TITLE
CLI: canuse-lite warning on build

### ISSUE THREAD

**Issue by jasonkneen** [tidev/titanium_mobile#13286]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

I get

```Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating```

on build

### Expected Behavior

Not getting this error

### Actual behavior

I get this error

### Reproducible sample

Build an app in 10.1.1

### Steps to reproduce

Build an app in 10.1.1

### Platform

CLI

### SDK version you are using

10.1.1

**Comment by m1ga** [comment]
Have this too. Glad you've made a ticket, always forgot about it :) 
There many node package updates we hopefully can merge soon!

This one is linked to https://github.com/appcelerator/node-titanium-sdk 
using `npm ls` inside the SDK root folder you'll see a graph.
