### ISSUE TITLE
iOS: dimBackgroundForSearch on TableView has no effect

### ISSUE THREAD

**Issue by caspahouzer** [tidev/titanium_mobile#13303]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

The dimBackgroundForSearch has ne effect on a TableView. The background is dimmed anyway.

Maybe related to https://github.com/tidev/titanium_mobile/issues/13246

### Expected Behavior

The background dimming should not be visible

### Actual behavior

The background dimming is visible when dimBackgroundForSearch=false

### Reproducible sample

```
const win = Ti.UI.createWindow({title: 'Window'});
var newData = Ti.UI.createTableViewRow({title: 'element 1'})
var newData2 = Ti.UI.createTableViewRow({title: 'row 2'})
var newData3 = Ti.UI.createTableViewRow({title: 'item 3'})
const table = Ti.UI.createTableView({
        dimBackgroundForSearch: false,
	search: Ti.UI.createSearchBar(),
	data: [newData, newData2, newData3]
});
win.add(table);
win.open();
``` 

### Steps to reproduce

- Start the example
- search for something

### Platform

iOS

### SDK version you are using

10.1.1.GA

**Comment by m1ga** [comment]
The connected PR fixed `fix top padding of dim-view in Ti.UI.TableView's search-bar` and not the `dimBackgroundForSearch` parameter. So I'll open this again as setting it to false doesn't hide the dim view.
