### ISSUE TITLE
Unable to compile for appstore - [ERROR] titanium_prep failed to run (10) 

### ISSUE THREAD

**Issue by angmon73** [tidev/titanium_mobile#13305]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

I have an old application, created with appcelerator some years ago. Because since the last march 1, it's impossible to use appcelerator anymore, I tried to compile my application using Titanium CLI commands. Before this, I installed the last Titanium CLI (npm install -g titanium latest) and I downloaded the 10.1.1.GA SDK.
I can start my application in iOS simulator, but using the Titanium CLI for building for appstore, I can see many compilation row messages, until the following red strings appears:
`[ERROR] titanium_prep failed to run (10)`
`[ERROR] This application cannot be built with the Titanium open source SDK because it is an Appcelerator Platform registered application. Please use the Appcelerator Platform CLI tools or Appcelerator Studio to build this application.`

Of course I cannot use the Appcelerator Platform CLI because it is expired.

Furthermore, in this application I'm using the Arrow (Axway - Appcelerator Backend) push notifications. Is there a way to distribute my app on app store mantaining the push notification functionality (I know they will expire on september 2022). If not; how to modify my app in order to distribuite it again on appstore?

Thank you in advance

### Expected Behavior

The expected behavior Is to build the application in order to upload it on App Store

### Actual behavior

Building process stops with errors

### Reproducible sample

No reproducible sample, because it applies on my project sources

### Steps to reproduce

No step to reproduce. I wrote all possible information in description above

### Platform

CLI

### SDK version you are using

10.1.1.GA

**Comment by angmon73** [comment]
Thank you very much @cb1kenobi. I will do what suggested in that guide, but I'm afraid about the push notifications once I'll have changed my guids....
Thank you again!!!

**Comment by cb1kenobi** [comment]
@angmon73 I'm not sure how push notifications are implemented. I highly recommend you hop on https://tidev.slack.com/ and ask in #helpme. There's a ton of people there that can help you. See you there!

**Comment by angmon73** [comment]
Thank you again. I tried to go on tidev.slack.com, but I was'nt able to access (I have a slack account, but when I try to go to that url  I receive an error about not having an account in the work area...)
However... thank you very much. I will try again on [tidev](https://tidev.slack.com/ a)

**Comment by m1ga** [comment]
@angmon73 use this link https://join.slack.com/t/tidev/shared_invite/zt-14qoze45t-Xx1NCSQ~akAEl70MVqjO_g

**Comment by m1ga** [comment]
@angmon73 and you might want to close this issue if its solved.

BTW: push notifications are not connected to the GUID

**Comment by angmon73** [comment]
Closed. Thank you very much
