### ISSUE TITLE
Android: OptionBar parity

### ISSUE THREAD

**Issue by caspahouzer** [tidev/titanium_mobile#13323]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

When I select a label from an [OptionBar](https://titaniumsdk.com/api/titanium/ui/optionbar.html) on iOS and programmatically set the index to -1, the OptionBar is deselected completely.

On Android, the OptionBar label stays selected

### Solution

The [OptionBar](https://titaniumsdk.com/api/titanium/ui/optionbar.html) should be in the unselected state like iOS.

Markers from @m1ga 
[default Value](https://github.com/tidev/titanium_mobile/blob/b3256959bf84a6fb2e3e86554cdc0867f0d533c3/android/modules/ui/src/java/ti/modules/titanium/ui/OptionBarProxy.java#L24) and [checkOption](https://github.com/tidev/titanium_mobile/blob/b3256959bf84a6fb2e3e86554cdc0867f0d533c3/android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIOptionBar.java#L105-L120)

### Platforms

Android & iOS

**Comment by hansemannn** [comment]
The default should remain as-is (to select the first element - I think that's also the case for iOS?), but the `checkOption` method could indeed be extended pretty easily. @caspahouzer Can you try that yourself?

**Comment by caspahouzer** [comment]
No, I have no idea of Java development. But I try it locally. If I really get it working, I make a PR and you comment how creepy I did it 😄

**Comment by m1ga** [comment]
PR at https://github.com/tidev/titanium_mobile/pull/13324
Test it with https://github.com/tidev/titanium_mobile/actions/runs/2028622443
