### ISSUE TITLE
iOS: DarkMode support for LaunchScreen Storyboard

### ISSUE THREAD

**Issue by caspahouzer** [tidev/titanium_mobile#13348]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

We need a DarkMode support for the app when using LaunchScreen Storyboard with `enable-launch-screen-storyboard` set to `true`

### Solution

The BackgroundColor of the `LaunchScreen.storyboard` must be set to `System Background Color` instead of `Custom`

Then the `app/assets/iphone/LaunchLogo*` can be used `app/assets/iphone/LaunchLogo-dark*`

### Alternatives

The only alternative is to get blended at night

### Platforms

iOS

**Comment by hansemannn** [comment]
For proper dark mode handling, you can set the color in the generated LaunchScreen.storyboard and place it into [app]/platform/ios/LaunchScreen.storyboard.

**Comment by hansemannn** [comment]
A possible PR could add a note to this behavior.
