### ISSUE TITLE
TiUIWebView does not handle NSURLAuthenticationMethodClientCertificate Challenge correctly

### ISSUE THREAD

**Issue by chauf** [tidev/titanium_mobile#13351]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

WebView Implementation does overwrite default handling for didReceiveAuthenticationChallenge methode and add some specials for ignoreSSLError flag etc.. Starting at line 880 you will find following code:
```js
// HTTPS in general
  } else if ([authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {
    completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
    // Default: Reject authentication challenge
  } else {
    completionHandler(NSURLSessionAuthChallengeCancelAuthenticationChallenge, nil);
  }
```

For some reason it fails for any other challenge then authenticationMethod = NSURLAuthenticationMethodServerTrust.
That fails any request that for example has a authenticationMethod = NSURLAuthenticationMethodClientCertificate or any other.

### Expected Behavior

Use NSURLSessionAuthChallengePerformDefaultHandling for any other challenge instead of canceling.

### Actual behavior

Fails any other challenge then NSURLAuthenticationMethodServerTrust.

### Reproducible sample
```js
$.webview.addEventListener(
        'error',
        function (e) {
            Ti.API.error('error: ' + e.error + '  Code: ' + e.code + ' BaseUrl' + e.url);
        }
);
$.webview.url = "https://device.login.microsoftonline.com";
```
### Steps to reproduce

Simply try to open https://device.login.microsoftonline.com in a webview.

### Platform

iOS

### SDK version you are using

10.1.1.GA

**Comment by chauf** [comment]
See PR: https://github.com/tidev/titanium_mobile/pull/13352

**Comment by m1ga** [comment]
Awesome :+1: PR and test, well done!
