### ISSUE TITLE
iOS: MediaModule use of undeclared identifier

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium_mobile#13396]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

When compiling an iOS store build the following error appeared in the trace log:
```
[TRACE] app/build/iphone/Classes/MediaModule.m:2180:28: error: use of undeclared identifier 'musicPicker'; did you mean 'mediaPicker_'?
[TRACE]     [self closeModalPicker:musicPicker];
[TRACE]                            ^~~~~~~~~~~
[TRACE]                            mediaPicker_
[TRACE] app/build/iphone/Classes/MediaModule.m:2177:48: note: 'mediaPicker_' declared here
[TRACE] - (void)mediaPicker:(MPMediaPickerController *)mediaPicker_ didPickMediaItems:(MPMediaItemCollection *)collection
[TRACE]                                                ^
[TRACE] app/build/iphone/Classes/MediaModule.m:2202:26: error: use of undeclared identifier 'musicPicker'; did you mean 'mediaPicker_'?
[TRACE]   [self closeModalPicker:musicPicker];
[TRACE]                          ^~~~~~~~~~~
[TRACE]                          mediaPicker_
[TRACE] app/build/iphone/Classes/MediaModule.m:2200:57: note: 'mediaPicker_' declared here
[TRACE] - (void)mediaPickerDidCancel:(MPMediaPickerController *)mediaPicker_
[TRACE]                                                         ^
[TRACE] 2 errors generated.
[TRACE]  
```
[Source in the SDK](https://github.com/tidev/titanium_mobile/blob/b3256959bf84a6fb2e3e86554cdc0867f0d533c3/iphone/Classes/MediaModule.m#L2173-L2203)

Simulator works fine, store build is failing

### Expected Behavior

no error

### Actual behavior

error

### Reproducible sample

**Test**
* create an empty app
* just add 
```js
 Ti.Media.queryMusicLibrary({
 	mediaType: {
 		value: Ti.Media.MUSIC_MEDIA_TYPE_MUSIC
 	}
 });
```
* make a store build

in case needed but I think its not needed to compile it:
```xml
<key>NSAppleMusicUsageDescription</key>
<string>Text</string>
```

### Steps to reproduce

build for store

### Platform

iOS

### SDK version you are using

10.1.1.GA

**Comment by m1ga** [comment]
when I change `mediaPicker_` to `musicPicker` in

https://github.com/tidev/titanium_mobile/blob/b3256959bf84a6fb2e3e86554cdc0867f0d533c3/iphone/Classes/MediaModule.m#L2175
and 

https://github.com/tidev/titanium_mobile/blob/b3256959bf84a6fb2e3e86554cdc0867f0d533c3/iphone/Classes/MediaModule.m#L2198

I can compile again. But I'm not sure if that will break any functionality.

**Comment by hansemannn** [comment]
How could that ever have happened?!
