### ISSUE TITLE
Ti.Platform.name return iPadOS for iPad 4th generation 

### ISSUE THREAD

**Issue by aviboy2006** [tidev/titanium_mobile#13420]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### URL

https://titaniumsdk.com/api/titanium/platform.html#name

### Description

for iPad 4th generation getting `iPadOS` as platform name. As per current document mentioned should return `iOS`. 

I checked most of iPad simulator returning `iPadOS`  as platform name. This got to know after upgrading new titanium 10.1.1 version.

### Suggestion

Add expected value for platform name is `iPadOS`

**Comment by hansemannn** [comment]
Addressed as part of https://github.com/tidev/titanium_mobile/commit/08450e3ecf9cdf9f15db3a05f50a30b57c8a3a9f, I hope thats fine now?

**Comment by aviboy2006** [comment]
Thanks for fixing this.
