### ISSUE TITLE
Push notifications issue

### ISSUE THREAD

**Issue by angmon73** [tidev/titanium_mobile#13451]
Hello to everyone.
In my Titanium app I use Push notifications and I read that this service (from Arrow) will expire in the next September. Unfortunately, starting from two weeks ago, my app doesn’t receive push notifications any more.

Any suggestions to implement new push notifications service in my Titanium app? Is there the possibility to use notifications from other providers? How? Any help will be appreciated.

**Comment by m1ga** [comment]
you can also check other Push providers like PubNub or Pushwoosh, they have a Titanium module too: 
https://www.pubnub.com/docs/sdks/javascript/titanium/changelog
https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium
But I've only used Firebase so far

**Comment by angmon73** [comment]
Thank you very much @m1ga.
I'll close the issue before to try, because I'm sure I can implement the solution as you suggested me.

**Comment by m1ga** [comment]
I've you are stuck or need any help feel free to open it again or ask in `#helpme` at https://slack.tidev.io/

**Comment by angmon73** [comment]
Thank you very much. I will study what you suggested me and then I'll come back :-)
