### ISSUE TITLE
Android: using tableView.data = arrayOfTableViewRows prevents tableView 'click' event listener from working

### ISSUE THREAD

**Issue by jfalcone** [tidev/titanium_mobile#13509]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

We're pretty sure we've experienced this bug many, many years ago on a previous re-implementation of TableView.

1. Create an arrayOfTableViewRows (simple or with children - it doesn't matter)
2. Create a TableView with data: arrayOfTableViewRows
3. [In our app implementation, we sort the arrayOfTableViewRows before the next step, but that is NOT required for the bug]
4. Assign tableView.data = arrayOfTableViewRows after the creation
5. Set tableView.addEventListener('click', function...)
6. Add tableView to window
7. Try clicking on tableView

Same behavior on emulators and devices.  Tested on Intel and M-series Macs.  Failures in all situations.

We've been using this feature in apps that are now 10-11 years old so it's been around a long time.  
Also works fine on iOS.
Purpose is to sort an existing tableView by different keys depending on user input while it is being displayed.
Workaround (if you can call it that) is to set a listener on every tableViewRow.

### Expected Behavior

tableView eventListener function is called on each click

### Actual behavior

The image of the row clicked visually responds to the click but the eventListener function is not called

### Reproducible sample

var win = Ti.UI.createWindow();

function randomInt(max) {
    return Math.floor(Math.random() * max) + 1;
}
var defaultFontSize = Ti.Platform.name === 'android' ? 16 : 14;
var tableData = [];

tableData = [];
for (var i = 1; i <= 20; i++) {
    var entryRow = Ti.UI.createTableViewRow({
        className: 'entryRowClass',
	title: randomInt(20),
        height: Ti.UI.SIZE
    });
    // our tableViewRows are more complex with children, etc but it turns out it doesn't matter for the bug
    tableData.push(entryRow);
}
console.log("set data");

var tableView = Ti.UI.createTableView({
    top: 0,
    data: tableData
});
/*
In our own application we sort the data before the assignment but it turns out that this doesn't matter
The Bug occurs regardless of whether or not you manipulate the tableData prior to the assignment to .data
We just include this comment here because you might think we are crazy to do the assignment after the creation.
*/
// tableData.sort(function(a, b) {
//     if (randomInt(20) > 10) return a; else return b;
// });

// this is the source of the trouble - comment this out and then the 'click' listener works
tableView.data = tableData;

tableView.addEventListener("click", function(e) {
    console.log(e.index);
});

win.add(tableView);
win.open();

// start clicking on the table - the row index should show up in the log but it doesn't because of the bug

### Steps to reproduce

1. Create an arrayOfTableViewRows (simple or with children - it doesn't matter)
2. Create a TableView with data: arrayOfTableViewRows
3. [We thought that an intermediate step was required to manipulate the arrayOfTableViews (e.g., sort on a key) as that is the situation in our own code but that is not required for the failure]
4. Assign tableView.data = arrayOfTableViewRows after the creation
5. Set tableView.addEventListener('click', function...)
6. Add tableView to window
7. Try clicking on the tableView - clicks are not received by the listener

### Platform

Android

### SDK version you are using

11.0.0.0

### Alloy version you are using

not alloy

**Comment by m1ga** [comment]
>  I have searched the existing issues

As you may know (because I've posted it in your slack thread) I've created the same thread right below yours: https://github.com/tidev/titanium_mobile/issues/13508 yesterday :wink: So I close this issue here since I've simplified the example a bit and also added some more info to it
