### ISSUE TITLE
Android slide does not have property to set left track tint color

### ISSUE THREAD

**Issue by mitulbhalia** [tidev/titanium_mobile#13520]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Slider does not have a property to set left track tint color.

Right now there is only property to set right track tint color is trackTintColor BUT can't set left track tint color...

### Solution

Slider should have property to set left track tint color.

### Alternatives

Right now we need to use custom theme to set it's left track color but we can set right track tint color using trackTintColor so there should be a property exist so that we can set left track tint color.

### Platforms

Android

**Comment by m1ga** [comment]
Fixed in https://github.com/tidev/titanium_mobile/pull/13518

just a documentation issue, it's in there since 8.3.0 :smile:
