### ISSUE TITLE
ti sdk install 11.0.0.GA = [ERROR] Failed to retrieve release

### ISSUE THREAD

**Issue by newportsolutionsgroup** [tidev/titanium_mobile#13527]
Has anyone else experience this issue as well?

ti sdk install 11.0.0.GA
```

[ERROR] Failed to retrieve release.
object null is not iterable (cannot read property Symbol(Symbol.iterator))
```

VS Code doesn't find any updates either not sure if that is related.

**Comment by cb1kenobi** [comment]
That was fixed here: https://github.com/tidev/titanium/pull/583. Please update your Titanium CLI.
