### ISSUE TITLE
Android: Modules build with 11.1.0.GA not working in apps

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium_mobile#13570]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Gradle tools in master were updated to 7.2.2. Building a module with it breaks apps:

```
[ERROR] E/ga.testfirebase: No implementation found for void com.williamrijksen.onesignal.TiModuleBootstrap.nativeBootstrap() (tried Java_com_williamrijksen_onesignal_TiModuleBootstrap_nativeBootstrap and Java_com_williamrijksen_onesignal_TiModuleBootstrap_nativeBootstrap__)
```

Lowering it back to 7.0.4 again makes it work again.

**Fix:**
11.1.X: https://github.com/tidev/titanium_mobile/pull/13572
Master: https://github.com/tidev/titanium_mobile/pull/13571

**Comment by hansemannn** [comment]
Do we know why Gradle 7.2.x breaks it? I would prefer to handle the newest version to not clash. And does it break all apps or only the ones that are < 11.1.0 but use modules built with >= 11.1.0?

**Comment by m1ga** [comment]
yes, its something with the order of the gradle tasks. I have some notes/findings in the old gradle update tickets and I've recently asked in the gradle forum for help https://discuss.gradle.org/t/build-order-problem-upgrading-build-tools-from-7-0-4-7-2-2/43850 

As mentioned in slack:
you can't start apps that have modules that are compiled with 11.1.0.GA. So it won't affect many users. Only those who have custom modules and they compiled them with 11.1.0.GA in the last week.

**Comment by m1ga** [comment]
the compile errors start as soon as you go to `com.android.tools.build:gradle:7.1.0` (current SDK is using 7.0.4 - https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google)

more infos on gradle updates: https://github.com/tidev/titanium_mobile#upgrade-gradle-and-gradle-plugin

some other issues with gradle updates/infos:
* https://github.com/tidev/titanium_mobile/pull/13443
* https://github.com/tidev/titanium_mobile/pull/12914 (cmake update infos)
* https://github.com/tidev/titanium_mobile/pull/12821
* https://github.com/tidev/titanium_mobile/pull/12185
