### ISSUE TITLE
Want to update README.md file and adding CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by Sowham-3098** [tidev/titanium_mobile#13602]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

I want to add how to contribute section and also contributors profile into main README.md file and want to add Code of conduct file.

### Solution

I will add this. Do You want this in your repo?

**Comment by m1ga** [comment]
Don't think that is needed here. The code of conduct is linked and we don't need the profiles in the readme.

But thank you for the request.
