### ISSUE TITLE
Create Code of Conduct for this repository

### ISSUE THREAD

**Issue by anjaligoswami** [tidev/titanium_mobile#13623]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### URL

https://github.com/tidev/titanium_mobile

### Description

I want to add a code of conduct file in this repository

### Suggestion

Hey, adding a code of conduct markdown file would be good for this repository.
If you could assign me this issue, then I can add it.
Thanks!

**Comment by m1ga** [comment]
Hi @anjaligoswami 
thank you for your request. If you have searched for the issue you would have found this one https://github.com/tidev/titanium_mobile/issues/13602 and we don't need a special code of conduct file.

I will close this one. Have a look at the other open issues to see if you can help with one of the Java/ObjectivC issues.

Thanks
