### ISSUE TITLE
Location status check (GPS enable / disable) check is failing on iPhone IOS 15.x and IOS 16.x

### ISSUE THREAD

**Issue by amarnathpatel** [tidev/titanium_mobile#13634]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Hi Team,

We have a titanium application built and deployed to Apple Store 4 years back using ti sdk 7.x .

It has function to check if iPhone device location is enabled or disabled.

Now location status check (GPS enable / disable) check is failing on iPhone IOS 15.x and IOS 16.x 

Could you please check for any any platform changes?

Thanks
Amar Nath

### Expected Behavior

Ti location check API should return correctlly  on iPhone IOS 15.x and IOS 16.x . It always returns false

### Actual behavior

Ti location check API  should return correctlly  on iPhone IOS 15.x and IOS 16.x a per device location is enabled or disabled.

### Reproducible sample

Ti location check API should return correctlly  on iPhone IOS 15.x and IOS 16.x a per device location is enabled or disabled.

### Steps to reproduce

Ti location check API should return correctlly  on iPhone IOS 15.x and IOS 16.x a per device location is enabled or disabled.

### Platform

iOS

### SDK version you are using

8.x

**Comment by m1ga** [comment]
can you tell us which method your are using to check it?

Also: 7.x is not supported anymore! It might use methods by Axway to do checks that have been shut down in November (announcement was made over a year ago). That version was released way before iOS 15/16 so if you want to support those devices you should update to the latest SDK.

**Comment by amarnathpatel** [comment]
Hi @m1ga  - Yes its Ti.Geolocation.locationServicesEnabled

var hasLocationPermissions = Ti.Geolocation.hasLocationPermissions(Ti.Geolocation.AUTHORIZATION_WHEN_IN_USE);
	if (hasLocationPermissions && Ti.Geolocation.locationServicesEnabled) {
   }

**Comment by amarnathpatel** [comment]
One update- Let me correct my previous comment. Ti SDK used is -8.x     <sdk-version>8.0.1.v20190408125832</sdk-version>
 I wrongly mentioend 7.x

**Comment by amarnathpatel** [comment]
Alos user alloy version is below-
<plugins>
        <plugin version="1.0">ti.alloy</plugin>
    </plugins>

**Comment by m1ga** [comment]
> One update- Let me correct my previous comment. Ti SDK used is -8.x 8.0.1.v20190408125832 I wrongly mentioend 7.x

doesn't make it really better :-) Still a 2019 SDK as you can see in the version name (should even be a nightly build).

As mentioned before: which keys do you use in your tiapp.xml to allow GPS permission?

**Comment by m1ga** [comment]
And I've just tested it on my device. Just:
`console.log(Ti.Geolocation.locationServicesEnabled)`
Ti 11.1.1.GA, iPhone 7, iOS 15.7.1
I see "true" and when I swtich to flight-mode I'll get "false". So as expected.

**Comment by amarnathpatel** [comment]
Ok thanks for update.. will check

**Comment by amarnathpatel** [comment]
> > One update- Let me correct my previous comment. Ti SDK used is -8.x 8.0.1.v20190408125832 I wrongly mentioend 7.x
> 
> doesn't make it really better :-) Still a 2019 SDK as you can see in the version name (should even be a nightly build).
> 
> As mentioned before: which keys do you use in your tiapp.xml to allow GPS permission?

Ok yes now, we are not using version but like 11.1.1.GA

**Comment by amarnathpatel** [comment]
> 

We have these keys in tiapp.xml  
<key>NSLocationWhenInUseUsageDescription</key>
     <string>App specific string.</string>
 <key>NSLocationAlwaysUsageDescription</key>
    <string>App specific string..</string>

**Comment by m1ga** [comment]
Just to sum up the old posts: there is no issue in the latest SDK and you are using an old unsupported SDK and not using the `NSLocationAlwaysAndWhenInUseUsageDescription` key but on older [deprecated key by Apple](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationalwaysusagedescription).
In my quick test on a device I didn't even need the keys to get the correct result (dev build to device).

There won't be any fix for older SDKs so the solution is that you'll need to update your app. 4 years without an update is a very long time. Lucky for you that it still worked till now but now you should update to the latest SDK.

I'll close this now but feel free to create a new one if you still have issues after you've updated your app
