### ISSUE TITLE
iOS: border gets bigger when setting borderRadius with multiple values

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium_mobile#13728]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Setting the borderRadius as an array for elements like View or Textfield will get bigger when you pause and resume the app.

```js
const win = Ti.UI.createWindow({});
const view = Ti.UI.createView({
	width: '94%',
	height: 40,
	borderColor: '#000',
	borderWidth: 1,
	borderRadius: [20, 0, 20, 0]
});
win.add(view);
win.open();
```

https://user-images.githubusercontent.com/4334997/214248377-26631b6a-ad09-4fd1-a838-01466e08d380.mp4

Won't happen with just `borderRadius: 20`

### Platform

iOS

### SDK version you are using

12.0.0.GA

**Comment by hansemannn** [comment]
Okay, so it's only happening when using edge-defined border-radii? Does it change something when using `'20 0 20 0'` instead?

**Comment by m1ga** [comment]
In Slack the original example was `borderRadius: '10px 10px'`  and its the same too. so it looks like its with all "non int" values

**Comment by hansemannn** [comment]
Okay. It's a regression from the dark mode layer changes I did a few months ago - will fix it tomorrow
