### ISSUE TITLE
Release Build failure on XCode 14.3

### ISSUE THREAD

**Issue by Lengualo** [tidev/titanium_mobile#13792]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Since updating to XCode 14.3, release builds now fail. Development builds to device work, which is odd. Downgrading XCode to 14.2 resolves the problem and builds succeed.

Ti SDK Version: 12.0.0 GA
XCode Version: 14.3
OS: Latest version of Mac OS
Editor: Pulsar with Titanium Package (Plugin): 3.0.3

Error Log: 
[ERROR] 2023-04-04 15:29:20.407 xcodebuild[3534:32724] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)

[ERROR] --- xcodebuild: WARNING: Using the first of multiple matching destinations:

[ERROR] { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }

[ERROR] { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }

[ERROR] { platform:iOS Simulator, id:44D63882-AD2E-49A0-960C-4750FF545BE8, OS:16.4, name:iPad (10th generation) }

[ERROR] { platform:iOS Simulator, id:E0FF4C53-2807-45F4-818F-523E98568E3B, OS:16.4, name:iPad Air (5th generation) }

[ERROR] { platform:iOS Simulator, id:78EF2D54-BC5C-41FC-BE5E-CA439F78B0E2, OS:16.4, name:iPad Pro (11-inch) (4th generation) }

[ERROR] { platform:iOS Simulator, id:F56D3192-CF4A-4C42-B83C-01BA5905A65C, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }

[ERROR] { platform:iOS Simulator, id:421DCA49-4CFA-416C-8A1A-3AA620A3FFB9, OS:16.4, name:iPad mini (6th generation) }

[ERROR] { platform:iOS Simulator, id:7EBDD2FB-161D-48D1-9D30-E586389E713C, OS:16.4, name:iPhone 14 }

[ERROR] { platform:iOS Simulator, id:65336A40-4DFE-4347-A5DA-0D38D446071A, OS:16.4, name:iPhone 14 Plus }

[ERROR] { platform:iOS Simulator, id:FC210D02-A42B-4FD7-B7BD-BB7823B43D2B, OS:16.4, name:iPhone 14 Pro }

[ERROR] { platform:iOS Simulator, id:21DD1C53-03D6-4575-8C20-42F2E03E2292, OS:16.4, name:iPhone 14 Pro Max }

[ERROR] { platform:iOS Simulator, id:27C00222-573C-4EE8-919A-17638BDB1066, OS:16.4, name:iPhone SE (3rd generation) }

[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEPLOYTYPE=production')

[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'LAUNCHSCREEN_STORYBOARD=1')

[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEFAULT_BGCOLOR_RED=1')

[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEFAULT_BGCOLOR_GREEN=1')

[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEFAULT_BGCOLOR_BLUE=1')

[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DISABLE_TI_LOG_SERVER=1')

[ERROR]  warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'TI_VERSION=12.0.0')

[ERROR] 2023-04-04 15:30:58.364 xcodebuild[3534:32724] Writing error result bundle to /var/folders/c3/rpp0xz453_qb6_6q3ffbskdc0000gp/T/ResultBundle_2023-04-04_15-30-0058.xcresult

[ERROR] xcodebuild: error: The file “BuildProductsPath” couldn’t be opened because there is no such file.: The operation couldn’t be completed. No such file or directory

Build failed. Process exited with code 1.

### Expected Behavior

Release build to succeed (always succeeded on XCode 14.2, fails on XCode 14.3).

### Actual behavior

Build fails with errors

### Reproducible sample

Does this with any app project

### Steps to reproduce

Try to do a release build on iOS using XCode 14.3

### SDK version you are using

12.0.0GA

**Comment by m1ga** [comment]
already merged in https://github.com/tidev/titanium_mobile/pull/13786
Please test that version in the first comment or downgrade to Xcode 14.2

**Comment by m1ga** [comment]
Closing this with the release of 12.1.0.GA. If you still have this issue with that version feel free to reply and I'll reopen it

**Comment by efeder-amd** [comment]
I am seeing this issue with xcode 14.3 and ti sdk 12.1.2.GA. Build details:

Operating System
  Name                        = macOS
  Version                     = 13.5.2
  Architecture                = 64bit
  # CPUs                      = 16
  Memory                      = 68719476736

Node.js
  Node.js Version             = 14.21.3
  npm Version                 = 6.14.18

Titanium CLI
  CLI Version                 = 6.1.1

Titanium SDK
  SDK Version                 = 12.1.2.GA
  Target Platform             = iphone

Command
  /Users/emilyfeder/.nvm/versions/node/v14.21.3/bin/node /Users/emilyfeder/.nvm/versions/node/v14.21.3/bin/ti build -p ios -T dist-adhoc

### Error:
```
[ERROR] 2023-09-26 09:33:44.882 xcodebuild[12370:8159281] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEPLOYTYPE=production')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'LAUNCHSCREEN_STORYBOARD=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEFAULT_BGCOLOR_RED=0.19607843137254902')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEFAULT_BGCOLOR_GREEN=0.2')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEFAULT_BGCOLOR_BLUE=0.2627450980392157')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DISABLE_TI_LOG_SERVER=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'TI_VERSION=12.1.2')
[ERROR] 2023-09-26 09:34:40.902 xcodebuild[12370:8159281] Writing error result bundle to /var/folders/10/1pk__yx54yd8_4tnrnmvbv200000gn/T/ResultBundle_2023-26-09_09-34-0040.xcresult
[ERROR] xcodebuild: error: The file “BuildProductsPath” couldn’t be opened because there is no such file.: The operation couldn’t be completed. No such file or directory

```

The error did not occur once I downgraded to 14.2.
It's probably not worth fixing this as folks can downgrade to 14.2 and the next xCode version (15.0) is already out anyway, so that would be the next xCode version to target.

**Comment by m1ga** [comment]
@efeder-amd If you can test it at some point it would be great to know if 12.2.0GA + XCode 15 will work for you. We had another post in Slack that had the same error even with 12.2.0 but couldn't find any cause for that yet.

**Comment by efeder-amd** [comment]
I tested using 12.2.0.GA and xCode 15, but it failed, complaining it couldn't find an ios simulator runtime as well as the same "BuildProductsPath" error. 

```
[ERROR] 2023-09-26 19:44:20.085 xcodebuild[77102:8862799] Unable to locate a bundle at URL file:///Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/
[ERROR] 2023-09-26 19:44:20.669 xcodebuild[77102:8862776] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22267/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
[ERROR] Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
[ERROR] Function: createItemModels(for:itemModelSource:)
[ERROR] Thread:   <_NSMainThread: 0x600003ac0180>{number = 1, name = main}
...
[ERROR] 2023-09-26 19:45:09.152 xcodebuild[77102:8862776] Writing error result bundle to /var/folders/10/1pk__yx54yd8_4tnrnmvbv200000gn/T/ResultBundle_2023-26-09_19-45-0009.xcresult
[ERROR] xcodebuild: error: The file “BuildProductsPath” couldn’t be opened because there is no such file.: The operation couldn’t be completed. No such file or directory
```
`ti info` does list simulators, including ones for iOS 17.

**Comment by Teunozz** [comment]
I seem to have the same issue with XCode 15 & Ti 12.2.0. I'am able to build to application without any issue if I change line 3282 in `12.2.0.GA\iphone\cli\commands\_build.js` though.

```
// const buildProductsPath = path.join(this.buildDir, 'DerivedData', 'Build', 'Intermediates.noindex', 'ArchiveIntermediates', this.sanitizedAppName(), 'BuildProductsPath');

// change to

const buildProductsPath = path.join(this.buildDir, 'Build', 'Intermediates', 'ArchiveIntermediates', this.sanitizedAppName(), 'BuildProductsPath');
```
The DerivedData folder doesn't have a Build folder in my case, not sure why.

**Comment by grantges** [comment]
In my case the above fix didn't work, however I was able to make a small modification build successsfully. Change I made to the same line of code (3282) mentioned above.

```
// const buildProductsPath = path.join(this.buildDir, 'DerivedData', 'Build', 'Intermediates.noindex', 'ArchiveIntermediates', this.sanitizedAppName(), 'BuildProductsPath');

// change to

const buildProductsPath = path.join(this.buildDir, 'Build', 'Intermediates.noindex', 'ArchiveIntermediates', this.sanitizedAppName(), 'BuildProductsPath');
```
For some reason referencing `Intermediates` didn't work, but `Intermediates.noindex` does. It's odd as I do see the build folder in `Intermediates` so not sure if this is a symlinked area or not.
