### ISSUE TITLE
Cannot build for iOS Store or Ad Hoc

### ISSUE THREAD

**Issue by alexlarocca** [tidev/titanium_mobile#13828]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

The app runs properly on iOS simulator but fails to build for App Store or Ad Hoc even using the latest Ti SDK 12.1.1.GA. It was working properly before to upgrade XCode to version 14.3. 

Tried also cleaning the project, deleteing the build folder and other folders outside app (alloy). Also tried recreating provisioning profiles and disabling all the modules.
[ti_build_log.txt](https://github.com/tidev/titanium_mobile/files/11420953/ti_build_log.txt)
[ti_info.txt](https://github.com/tidev/titanium_mobile/files/11420957/ti_info.txt)

### Expected Behavior

I expect to build the app

### Actual behavior

The app does not build for iOS App Store or Ad Hoc

### Reproducible sample

not applicable

### Steps to reproduce

not applicable

### Platform

iOS

### SDK version you are using

12.1.1.GA

**Comment by alexlarocca** [comment]
Downgrading to XCode 14.2 solves the issue. So the combination XCode 14.3 and Ti SDK 12.1.1 still does not work in some cases.

**Comment by hansemannn** [comment]
Hi there! Would you be able to provide a reproducible test project? I assume it could be the space in the project name. Temporarily removing that may help, but a test case would be really helpful.

**Comment by hansemannn** [comment]
Fix: https://github.com/tidev/titanium_mobile/pull/13832
